# Generated by Django 3.2.13 on 2022-05-22 19:16

import agenda.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(unique=True)),
            ],
            options={
                'ordering': ['horario'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(validators=[agenda.models.Agenda.validate_date])),
                ('horarios', models.ManyToManyField(to='agenda.Horario')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='medico.medico')),
            ],
            options={
                'ordering': ['dia'],
            },
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('medico', 'dia'), name='unique_entry_agenda'),
        ),
    ]
