# Generated by Django 3.2.13 on 2022-05-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='trello_card_id',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
